require "spec_helper"

RSpec.describe "Decimal contract" do
  it "loads BigDecimal as a runtime dependency" do
    expect { require "bigdecimal" }.not_to raise_error
    expect(defined?(BigDecimal)).to be_truthy
  end

  it "parses decimal model attributes as BigDecimal" do
    models_dir = File.expand_path("../lib/files.com/models", __dir__)
    model_files = Dir.glob(File.join(models_dir, "*.rb"))

    decimal_getter = nil

    model_files.each do |path|
      src = File.read(path)
      class_name = src[/class\s+(\w+)/, 1]
      next unless class_name

      # Match the decimal getter pattern generated by the templates.
      match = src.match(
        /def\s+(?<method>\w+)\n\s+value\s*=\s*@attributes\[:(?<attr>\w+)\]\n\s+return\s+value\s+if\s+value\.nil\?\s*\|\|\s+value\.is_a\?\(BigDecimal\)\n\n\s+BigDecimal\(value\.to_s\)/
      )

      next unless match

      decimal_getter = {
        class_name: class_name,
        method: match[:method],
        attr: match[:attr].to_sym,
      }
      break
    end

    expect(decimal_getter).not_to be_nil

    klass = Files.const_get(decimal_getter[:class_name])
    obj = klass.new({ decimal_getter[:attr] => "1.2300" })

    value = obj.public_send(decimal_getter[:method])
    expect(value).to be_a(BigDecimal)
    expect(value).to eq(BigDecimal("1.2300"))
  end
end
