# frozen_string_literal: true

module Files
  class AutomationLog
    attr_reader :options, :attributes

    def initialize(attributes = {}, options = {})
      @attributes = attributes || {}
      @options = options || {}
    end

    # date-time - Start Time of Action. Deprecrated: Use created_at.
    def timestamp
      @attributes[:timestamp]
    end

    # int64 - Automation ID
    def automation_id
      @attributes[:automation_id]
    end

    # int64 - Automation Run ID
    def automation_run_id
      @attributes[:automation_run_id]
    end

    # string - Destination path, for moves and copies
    def dest_path
      @attributes[:dest_path]
    end

    # string - Error type, if applicable
    def error_type
      @attributes[:error_type]
    end

    # string - Message
    def message
      @attributes[:message]
    end

    # string - Operation type
    def operation
      @attributes[:operation]
    end

    # string - File path. This must be slash-delimited, but it must neither start nor end with a slash. Maximum of 5000 characters.
    def path
      @attributes[:path]
    end

    # string - Status
    def status
      @attributes[:status]
    end

    # date-time - Start Time of Action
    def created_at
      @attributes[:created_at]
    end

    # Parameters:
    #   cursor - string - Used for pagination.  When a list request has more records available, cursors are provided in the response headers `X-Files-Cursor-Next` and `X-Files-Cursor-Prev`.  Send one of those cursor value here to resume an existing list from the next available record.  Note: many of our SDKs have iterator methods that will automatically handle cursor-based pagination.
    #   per_page - int64 - Number of records to show per page.  (Max: 10,000, 1,000 or less is recommended).
    #   filter - object - If set, return records where the specified field is equal to the supplied value. Valid fields are `automation_id`, `automation_run_id`, `operation`, `path`, `status` or `created_at`. Valid field combinations are `[ automation_id ]`, `[ automation_run_id ]`, `[ operation ]`, `[ path ]`, `[ status ]`, `[ created_at ]`, `[ automation_id, automation_run_id ]`, `[ automation_id, operation ]`, `[ automation_id, path ]`, `[ automation_id, status ]`, `[ automation_id, created_at ]`, `[ automation_run_id, operation ]`, `[ automation_run_id, path ]`, `[ automation_run_id, status ]`, `[ automation_run_id, created_at ]`, `[ operation, path ]`, `[ operation, status ]`, `[ operation, created_at ]`, `[ path, status ]`, `[ path, created_at ]`, `[ status, created_at ]`, `[ automation_id, automation_run_id, operation ]`, `[ automation_id, automation_run_id, path ]`, `[ automation_id, automation_run_id, status ]`, `[ automation_id, automation_run_id, created_at ]`, `[ automation_id, operation, path ]`, `[ automation_id, operation, status ]`, `[ automation_id, operation, created_at ]`, `[ automation_id, path, status ]`, `[ automation_id, path, created_at ]`, `[ automation_id, status, created_at ]`, `[ automation_run_id, operation, path ]`, `[ automation_run_id, operation, status ]`, `[ automation_run_id, operation, created_at ]`, `[ automation_run_id, path, status ]`, `[ automation_run_id, path, created_at ]`, `[ automation_run_id, status, created_at ]`, `[ operation, path, status ]`, `[ operation, path, created_at ]`, `[ operation, status, created_at ]`, `[ path, status, created_at ]`, `[ automation_id, automation_run_id, operation, path ]`, `[ automation_id, automation_run_id, operation, status ]`, `[ automation_id, automation_run_id, operation, created_at ]`, `[ automation_id, automation_run_id, path, status ]`, `[ automation_id, automation_run_id, path, created_at ]`, `[ automation_id, automation_run_id, status, created_at ]`, `[ automation_id, operation, path, status ]`, `[ automation_id, operation, path, created_at ]`, `[ automation_id, operation, status, created_at ]`, `[ automation_id, path, status, created_at ]`, `[ automation_run_id, operation, path, status ]`, `[ automation_run_id, operation, path, created_at ]`, `[ automation_run_id, operation, status, created_at ]`, `[ automation_run_id, path, status, created_at ]`, `[ operation, path, status, created_at ]`, `[ automation_id, automation_run_id, operation, path, status ]`, `[ automation_id, automation_run_id, operation, path, created_at ]`, `[ automation_id, automation_run_id, operation, status, created_at ]`, `[ automation_id, automation_run_id, path, status, created_at ]`, `[ automation_id, operation, path, status, created_at ]`, `[ automation_run_id, operation, path, status, created_at ]` or `[ automation_id, automation_run_id, operation, path, status, created_at ]`.
    #   filter_gt - object - If set, return records where the specified field is greater than the supplied value. Valid fields are `created_at`. Valid field combinations are `[ automation_id ]`, `[ automation_run_id ]`, `[ operation ]`, `[ path ]`, `[ status ]`, `[ created_at ]`, `[ automation_id, automation_run_id ]`, `[ automation_id, operation ]`, `[ automation_id, path ]`, `[ automation_id, status ]`, `[ automation_id, created_at ]`, `[ automation_run_id, operation ]`, `[ automation_run_id, path ]`, `[ automation_run_id, status ]`, `[ automation_run_id, created_at ]`, `[ operation, path ]`, `[ operation, status ]`, `[ operation, created_at ]`, `[ path, status ]`, `[ path, created_at ]`, `[ status, created_at ]`, `[ automation_id, automation_run_id, operation ]`, `[ automation_id, automation_run_id, path ]`, `[ automation_id, automation_run_id, status ]`, `[ automation_id, automation_run_id, created_at ]`, `[ automation_id, operation, path ]`, `[ automation_id, operation, status ]`, `[ automation_id, operation, created_at ]`, `[ automation_id, path, status ]`, `[ automation_id, path, created_at ]`, `[ automation_id, status, created_at ]`, `[ automation_run_id, operation, path ]`, `[ automation_run_id, operation, status ]`, `[ automation_run_id, operation, created_at ]`, `[ automation_run_id, path, status ]`, `[ automation_run_id, path, created_at ]`, `[ automation_run_id, status, created_at ]`, `[ operation, path, status ]`, `[ operation, path, created_at ]`, `[ operation, status, created_at ]`, `[ path, status, created_at ]`, `[ automation_id, automation_run_id, operation, path ]`, `[ automation_id, automation_run_id, operation, status ]`, `[ automation_id, automation_run_id, operation, created_at ]`, `[ automation_id, automation_run_id, path, status ]`, `[ automation_id, automation_run_id, path, created_at ]`, `[ automation_id, automation_run_id, status, created_at ]`, `[ automation_id, operation, path, status ]`, `[ automation_id, operation, path, created_at ]`, `[ automation_id, operation, status, created_at ]`, `[ automation_id, path, status, created_at ]`, `[ automation_run_id, operation, path, status ]`, `[ automation_run_id, operation, path, created_at ]`, `[ automation_run_id, operation, status, created_at ]`, `[ automation_run_id, path, status, created_at ]`, `[ operation, path, status, created_at ]`, `[ automation_id, automation_run_id, operation, path, status ]`, `[ automation_id, automation_run_id, operation, path, created_at ]`, `[ automation_id, automation_run_id, operation, status, created_at ]`, `[ automation_id, automation_run_id, path, status, created_at ]`, `[ automation_id, operation, path, status, created_at ]`, `[ automation_run_id, operation, path, status, created_at ]` or `[ automation_id, automation_run_id, operation, path, status, created_at ]`.
    #   filter_gteq - object - If set, return records where the specified field is greater than or equal the supplied value. Valid fields are `created_at`. Valid field combinations are `[ automation_id ]`, `[ automation_run_id ]`, `[ operation ]`, `[ path ]`, `[ status ]`, `[ created_at ]`, `[ automation_id, automation_run_id ]`, `[ automation_id, operation ]`, `[ automation_id, path ]`, `[ automation_id, status ]`, `[ automation_id, created_at ]`, `[ automation_run_id, operation ]`, `[ automation_run_id, path ]`, `[ automation_run_id, status ]`, `[ automation_run_id, created_at ]`, `[ operation, path ]`, `[ operation, status ]`, `[ operation, created_at ]`, `[ path, status ]`, `[ path, created_at ]`, `[ status, created_at ]`, `[ automation_id, automation_run_id, operation ]`, `[ automation_id, automation_run_id, path ]`, `[ automation_id, automation_run_id, status ]`, `[ automation_id, automation_run_id, created_at ]`, `[ automation_id, operation, path ]`, `[ automation_id, operation, status ]`, `[ automation_id, operation, created_at ]`, `[ automation_id, path, status ]`, `[ automation_id, path, created_at ]`, `[ automation_id, status, created_at ]`, `[ automation_run_id, operation, path ]`, `[ automation_run_id, operation, status ]`, `[ automation_run_id, operation, created_at ]`, `[ automation_run_id, path, status ]`, `[ automation_run_id, path, created_at ]`, `[ automation_run_id, status, created_at ]`, `[ operation, path, status ]`, `[ operation, path, created_at ]`, `[ operation, status, created_at ]`, `[ path, status, created_at ]`, `[ automation_id, automation_run_id, operation, path ]`, `[ automation_id, automation_run_id, operation, status ]`, `[ automation_id, automation_run_id, operation, created_at ]`, `[ automation_id, automation_run_id, path, status ]`, `[ automation_id, automation_run_id, path, created_at ]`, `[ automation_id, automation_run_id, status, created_at ]`, `[ automation_id, operation, path, status ]`, `[ automation_id, operation, path, created_at ]`, `[ automation_id, operation, status, created_at ]`, `[ automation_id, path, status, created_at ]`, `[ automation_run_id, operation, path, status ]`, `[ automation_run_id, operation, path, created_at ]`, `[ automation_run_id, operation, status, created_at ]`, `[ automation_run_id, path, status, created_at ]`, `[ operation, path, status, created_at ]`, `[ automation_id, automation_run_id, operation, path, status ]`, `[ automation_id, automation_run_id, operation, path, created_at ]`, `[ automation_id, automation_run_id, operation, status, created_at ]`, `[ automation_id, automation_run_id, path, status, created_at ]`, `[ automation_id, operation, path, status, created_at ]`, `[ automation_run_id, operation, path, status, created_at ]` or `[ automation_id, automation_run_id, operation, path, status, created_at ]`.
    #   filter_prefix - object - If set, return records where the specified field is prefixed by the supplied value. Valid fields are `operation`, `path` or `status`. Valid field combinations are `[ automation_id ]`, `[ automation_run_id ]`, `[ operation ]`, `[ path ]`, `[ status ]`, `[ created_at ]`, `[ automation_id, automation_run_id ]`, `[ automation_id, operation ]`, `[ automation_id, path ]`, `[ automation_id, status ]`, `[ automation_id, created_at ]`, `[ automation_run_id, operation ]`, `[ automation_run_id, path ]`, `[ automation_run_id, status ]`, `[ automation_run_id, created_at ]`, `[ operation, path ]`, `[ operation, status ]`, `[ operation, created_at ]`, `[ path, status ]`, `[ path, created_at ]`, `[ status, created_at ]`, `[ automation_id, automation_run_id, operation ]`, `[ automation_id, automation_run_id, path ]`, `[ automation_id, automation_run_id, status ]`, `[ automation_id, automation_run_id, created_at ]`, `[ automation_id, operation, path ]`, `[ automation_id, operation, status ]`, `[ automation_id, operation, created_at ]`, `[ automation_id, path, status ]`, `[ automation_id, path, created_at ]`, `[ automation_id, status, created_at ]`, `[ automation_run_id, operation, path ]`, `[ automation_run_id, operation, status ]`, `[ automation_run_id, operation, created_at ]`, `[ automation_run_id, path, status ]`, `[ automation_run_id, path, created_at ]`, `[ automation_run_id, status, created_at ]`, `[ operation, path, status ]`, `[ operation, path, created_at ]`, `[ operation, status, created_at ]`, `[ path, status, created_at ]`, `[ automation_id, automation_run_id, operation, path ]`, `[ automation_id, automation_run_id, operation, status ]`, `[ automation_id, automation_run_id, operation, created_at ]`, `[ automation_id, automation_run_id, path, status ]`, `[ automation_id, automation_run_id, path, created_at ]`, `[ automation_id, automation_run_id, status, created_at ]`, `[ automation_id, operation, path, status ]`, `[ automation_id, operation, path, created_at ]`, `[ automation_id, operation, status, created_at ]`, `[ automation_id, path, status, created_at ]`, `[ automation_run_id, operation, path, status ]`, `[ automation_run_id, operation, path, created_at ]`, `[ automation_run_id, operation, status, created_at ]`, `[ automation_run_id, path, status, created_at ]`, `[ operation, path, status, created_at ]`, `[ automation_id, automation_run_id, operation, path, status ]`, `[ automation_id, automation_run_id, operation, path, created_at ]`, `[ automation_id, automation_run_id, operation, status, created_at ]`, `[ automation_id, automation_run_id, path, status, created_at ]`, `[ automation_id, operation, path, status, created_at ]`, `[ automation_run_id, operation, path, status, created_at ]` or `[ automation_id, automation_run_id, operation, path, status, created_at ]`.
    #   filter_lt - object - If set, return records where the specified field is less than the supplied value. Valid fields are `created_at`. Valid field combinations are `[ automation_id ]`, `[ automation_run_id ]`, `[ operation ]`, `[ path ]`, `[ status ]`, `[ created_at ]`, `[ automation_id, automation_run_id ]`, `[ automation_id, operation ]`, `[ automation_id, path ]`, `[ automation_id, status ]`, `[ automation_id, created_at ]`, `[ automation_run_id, operation ]`, `[ automation_run_id, path ]`, `[ automation_run_id, status ]`, `[ automation_run_id, created_at ]`, `[ operation, path ]`, `[ operation, status ]`, `[ operation, created_at ]`, `[ path, status ]`, `[ path, created_at ]`, `[ status, created_at ]`, `[ automation_id, automation_run_id, operation ]`, `[ automation_id, automation_run_id, path ]`, `[ automation_id, automation_run_id, status ]`, `[ automation_id, automation_run_id, created_at ]`, `[ automation_id, operation, path ]`, `[ automation_id, operation, status ]`, `[ automation_id, operation, created_at ]`, `[ automation_id, path, status ]`, `[ automation_id, path, created_at ]`, `[ automation_id, status, created_at ]`, `[ automation_run_id, operation, path ]`, `[ automation_run_id, operation, status ]`, `[ automation_run_id, operation, created_at ]`, `[ automation_run_id, path, status ]`, `[ automation_run_id, path, created_at ]`, `[ automation_run_id, status, created_at ]`, `[ operation, path, status ]`, `[ operation, path, created_at ]`, `[ operation, status, created_at ]`, `[ path, status, created_at ]`, `[ automation_id, automation_run_id, operation, path ]`, `[ automation_id, automation_run_id, operation, status ]`, `[ automation_id, automation_run_id, operation, created_at ]`, `[ automation_id, automation_run_id, path, status ]`, `[ automation_id, automation_run_id, path, created_at ]`, `[ automation_id, automation_run_id, status, created_at ]`, `[ automation_id, operation, path, status ]`, `[ automation_id, operation, path, created_at ]`, `[ automation_id, operation, status, created_at ]`, `[ automation_id, path, status, created_at ]`, `[ automation_run_id, operation, path, status ]`, `[ automation_run_id, operation, path, created_at ]`, `[ automation_run_id, operation, status, created_at ]`, `[ automation_run_id, path, status, created_at ]`, `[ operation, path, status, created_at ]`, `[ automation_id, automation_run_id, operation, path, status ]`, `[ automation_id, automation_run_id, operation, path, created_at ]`, `[ automation_id, automation_run_id, operation, status, created_at ]`, `[ automation_id, automation_run_id, path, status, created_at ]`, `[ automation_id, operation, path, status, created_at ]`, `[ automation_run_id, operation, path, status, created_at ]` or `[ automation_id, automation_run_id, operation, path, status, created_at ]`.
    #   filter_lteq - object - If set, return records where the specified field is less than or equal the supplied value. Valid fields are `created_at`. Valid field combinations are `[ automation_id ]`, `[ automation_run_id ]`, `[ operation ]`, `[ path ]`, `[ status ]`, `[ created_at ]`, `[ automation_id, automation_run_id ]`, `[ automation_id, operation ]`, `[ automation_id, path ]`, `[ automation_id, status ]`, `[ automation_id, created_at ]`, `[ automation_run_id, operation ]`, `[ automation_run_id, path ]`, `[ automation_run_id, status ]`, `[ automation_run_id, created_at ]`, `[ operation, path ]`, `[ operation, status ]`, `[ operation, created_at ]`, `[ path, status ]`, `[ path, created_at ]`, `[ status, created_at ]`, `[ automation_id, automation_run_id, operation ]`, `[ automation_id, automation_run_id, path ]`, `[ automation_id, automation_run_id, status ]`, `[ automation_id, automation_run_id, created_at ]`, `[ automation_id, operation, path ]`, `[ automation_id, operation, status ]`, `[ automation_id, operation, created_at ]`, `[ automation_id, path, status ]`, `[ automation_id, path, created_at ]`, `[ automation_id, status, created_at ]`, `[ automation_run_id, operation, path ]`, `[ automation_run_id, operation, status ]`, `[ automation_run_id, operation, created_at ]`, `[ automation_run_id, path, status ]`, `[ automation_run_id, path, created_at ]`, `[ automation_run_id, status, created_at ]`, `[ operation, path, status ]`, `[ operation, path, created_at ]`, `[ operation, status, created_at ]`, `[ path, status, created_at ]`, `[ automation_id, automation_run_id, operation, path ]`, `[ automation_id, automation_run_id, operation, status ]`, `[ automation_id, automation_run_id, operation, created_at ]`, `[ automation_id, automation_run_id, path, status ]`, `[ automation_id, automation_run_id, path, created_at ]`, `[ automation_id, automation_run_id, status, created_at ]`, `[ automation_id, operation, path, status ]`, `[ automation_id, operation, path, created_at ]`, `[ automation_id, operation, status, created_at ]`, `[ automation_id, path, status, created_at ]`, `[ automation_run_id, operation, path, status ]`, `[ automation_run_id, operation, path, created_at ]`, `[ automation_run_id, operation, status, created_at ]`, `[ automation_run_id, path, status, created_at ]`, `[ operation, path, status, created_at ]`, `[ automation_id, automation_run_id, operation, path, status ]`, `[ automation_id, automation_run_id, operation, path, created_at ]`, `[ automation_id, automation_run_id, operation, status, created_at ]`, `[ automation_id, automation_run_id, path, status, created_at ]`, `[ automation_id, operation, path, status, created_at ]`, `[ automation_run_id, operation, path, status, created_at ]` or `[ automation_id, automation_run_id, operation, path, status, created_at ]`.
    def self.list(params = {}, options = {})
      raise InvalidParameterError.new("Bad parameter: cursor must be an String") if params[:cursor] and !params[:cursor].is_a?(String)
      raise InvalidParameterError.new("Bad parameter: per_page must be an Integer") if params[:per_page] and !params[:per_page].is_a?(Integer)
      raise InvalidParameterError.new("Bad parameter: filter must be an Hash") if params[:filter] and !params[:filter].is_a?(Hash)
      raise InvalidParameterError.new("Bad parameter: filter_gt must be an Hash") if params[:filter_gt] and !params[:filter_gt].is_a?(Hash)
      raise InvalidParameterError.new("Bad parameter: filter_gteq must be an Hash") if params[:filter_gteq] and !params[:filter_gteq].is_a?(Hash)
      raise InvalidParameterError.new("Bad parameter: filter_prefix must be an Hash") if params[:filter_prefix] and !params[:filter_prefix].is_a?(Hash)
      raise InvalidParameterError.new("Bad parameter: filter_lt must be an Hash") if params[:filter_lt] and !params[:filter_lt].is_a?(Hash)
      raise InvalidParameterError.new("Bad parameter: filter_lteq must be an Hash") if params[:filter_lteq] and !params[:filter_lteq].is_a?(Hash)

      List.new(AutomationLog, params) do
        Api.send_request("/automation_logs", :get, params, options)
      end
    end

    def self.all(params = {}, options = {})
      list(params, options)
    end
  end
end
